[package]
name = "printcountpay-core"
version.workspace = true
edition.workspace = true

[dependencies]
get_if_addrs.workspace = true
ron.workspace = true
serde.workspace = true
snmp.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
